from django.core.mail import send_mail
from django.conf import settings



def send_forgot_password_email(email,token,host,encoded_email):
    subject = 'Reset Your Password link.'
    
    reset_link = settings.FORGOT_PASSWORD_HOST+f'/#/reset-password/{token},{encoded_email}/'

    message = f''' 
Hello,
Please click on the folowing link to reset your password. 
{reset_link}

Regards,
IDia


Please do not reply directly to this autogenerated email. If you have any questions or concerns, please contact Link Intime.
               '''
    email_from = settings.EMAIL_HOST_USER
    to = [email]
    send_mail(subject,message,email_from,to)
    return True